config/routes.rb
Rails.application.routes.draw do

  resources :comentarios

  devise_for :users, controllers: {
    sessions: 'users/sessions'

  }
  
  resources :posts do 
    resources :comentarios
  end

  root "posts#index"

end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  #Association for Post
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base

	# Association for comentarios
	has_many :comentario

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @comentarios = Comentario.all
    respond_with(@comentarios)
  end

  def show
    respond_with(@comentario)
  end

  def new
    @comentario = Comentario.new
    @post = Post.new(params[:post_id])
    respond_with(@comentario)
  end

  def edit
  end

  def create
    @post = Post.find(params[:post_id])
    @comentarios = @post.comentarios.create(comentario_params)
    redirect_to posts_path(@post)
    #@comentario = Comentario.new(comentario_params)
    #@comentario.save
    #respond_with(@comentario)
  end

  def update
    @comentario.update(comentario_params)
    respond_with(@comentario)
  end

  def destroy
    @comentario.destroy
    respond_with(@comentario)
  end

  private
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    def comentario_params
      params.require(:comentario).permit(:nome, :corpo, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:titulo, :corpo, :categoria, :autor)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
   def new
     super
   end

  # POST /resource/password
   def create
     super
   end

  # GET /resource/password/edit?reset_password_token=abcdef
   def edit
     super
   end

  # PUT /resource/password
   def update
     super
   end
 
  # protected

   def after_resetting_password_path_for(resource)
     super(resource)
   end

  # The path used after sending reset password instructions
   def after_sending_reset_password_instructions_path_for(resource_name)
     super(resource_name)
   end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 before_filter :configure_sign_up_params, only: [:create]
 before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
   def new
     super
   end

  # POST /resource
  def create
     super
  end

  # GET /resource/edit
   def edit
     super
   end

  # PUT /resource
   def update
     super
   end

  # DELETE /resource
   def destroy
     super
   end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
   def cancel
     super
   end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.for(:sign_up) << :attribute
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.for(:account_update) << :attribute
   end

   The path used after sign up.
   def after_sign_up_path_for(resource)
     super(resource)
   end

   The path used after sign up for inactive accounts.
   def after_inactive_sign_up_path_for(resource)
    super(resource)
   end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
   def new
     super
   end

  # POST /resource/sign_in
   def create
     super
   end

  # DELETE /resource/sign_out
   def destroy
     super
   end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_in_params
     devise_parameter_sanitizer.for(:sign_in) << :attribute
   end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper

#  def resource_name
#    :user
#  end

#  def resource
#    @resource ||= User.new
#  end

#  def devise_mapping
#    @devise_mapping ||= Devise.mappings[:user]
#  end

end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comentarios/_form.html.erb
<%= form_for(@comentario, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @comentario.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h4>

      <ul>
      <% @comentario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :corpo, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :corpo, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :post, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :post, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<div class="page-header">
  <%= link_to comentarios_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @comentario, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing comentario</h1>
</div>

<%= render 'form' %>

app/views/comentarios/index.html.erb
<div class="page-header">
  <%= link_to new_comentario_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Comentario
  <% end %>
  <h1>Listing comentarios</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Nome</th>
            <th>Corpo</th>
            <th>Post</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @comentarios) do |comentario| %>
            <td><%= comentario.nome %></td>
            <td><%= comentario.corpo %></td>
            <td><%= comentario.post %></td>
            <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/comentarios/new.html.erb
<div class="page-header">
  <%= link_to comentarios_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New comentario</h1>
</div>

<%= render 'form' %>

app/views/comentarios/show.html.erb
<div class="page-header">
  <%= link_to comentarios_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_comentario_path(@comentario), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show comentario</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @comentario.nome %></dd>

  <dt>Corpo:</dt>
  <dd><%= @comentario.corpo %></dd>

  <dt>Post:</dt>
  <dd><%= @comentario.post %></dd>

</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Rails Blog</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- Bootstrap navbar -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Rails Blog", posts_path, class: "navbar-brand" %>
      </div>

        <!-- Area de notificacao de membro (users/sessions) -->
        <div class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logado como <strong><%= current_user.email %></strong>.
          <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Registrar-se", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Entrar", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
        </div>
        <!-- |FIM| Area de notificacao de membro -->

      <!-- paginas do blog -->  
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", posts_path %></li>
          <li class=""> <%= link_to "Pagina 1", posts_path %> </li>
          <li class=""> <%= link_to "Pagina 2", posts_path %> </li>
          <li class=""> <%= link_to "Pagina 3", posts_path %> </li>
          <li class=""> <%= link_to "Pagina 4", posts_path %> </li>
          <li class=""> <%= link_to "Pagina 5", posts_path %> </li>
        </ul>
      </div>
      <!-- |FIM| paginas do blog -->

    </div>
  </nav>
  <!-- Bootstrap navbar -->

<div class="container">

  <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= msg %>
      <% end %>
  <% end %>

  <div class="row">
    <!-- Carousel/Silder -->
    <div id="mainSlider" class="col-lg-12">
        <div class="container">
        <br>
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="3"></li>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <img src="http://s1.postimg.org/ghytal53z/1252x452_img1.png" alt="Imagem 1" width="1252" height="452">
            </div>

            <div class="item">
              <img src="http://s1.postimg.org/ghytal53z/1252x452_img1.png" alt="Imagem 2" width="1252" height="452">
            </div>

            <div class="item">
              <img src="http://s1.postimg.org/ghytal53z/1252x452_img1.png" alt="Imagem 3" width="1252" height="452">
            </div>

            <div class="item">
              <img src="http://s1.postimg.org/ghytal53z/1252x452_img1.png" alt="Imagem 4" width="1252" height="452">
            </div>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a></div></div></div></div>
  </br>

  <!--| Main & Sidebar |-->
  <div class="row">

        <div class="col-md-8">
         <!-- Main frame as yield -->
         <%= yield %>
        </div>

        <div class="col-md-4">

          <!-- Blog Search / Procurar -->
          <div class="well">
            <h4>Procurar no blog</h4>
            <div class="input-group">
              <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                              <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </span>
            </div>
            <!-- /.input-group --></div>
          <!-- Blog Search / Procurar -->

          <!-- Categorias do Blog -->
          <div class="well">
            <h4>Blog Categories</h4>
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled">
                  <li><a href="#">Category Name</a>
                  </li>
                  <li><a href="#">Category Name</a>
                  </li>
                  <li><a href="#">Category Name</a>
                  </li>
                  <li><a href="#">Category Name</a>
                  </li>
                </ul>
              </div>
              <!-- /.col-lg-6 -->
              <div class="col-lg-6">
                <ul class="list-unstyled">
                  <li><a href="#">Category Name</a>
                  </li>
                  <li><a href="#">Category Name</a>
                  </li>
                  <li><a href="#">Category Name</a>
                  </li>
                  <li><a href="#">Category Name</a>
                  </li>
                </ul>
              </div>
              <!-- /.col-lg-6 -->
            </div>
            <!-- /.row --></div>
          <!-- Categorias do Blog -->

          <!-- Redes sociais -->
          <div class="well">
            <h4>Redes Sociais</h4>
            <p> Siga o blog nas redes sociais </p>

            <ul class="nav nav-pills nav-stacked">
              <li role="presentation" class=""><a href="https://www.facebook.com/lucas.thomaz.792">Facebook</a></li>
              <li role="presentation" class=""><a href="https://www.twitter.com/lucasmrthomaz">Twitter</a></li>
              <li role="presentation" class=""><a href="https://www.youtube.com/channel/UCEJaR7aSVLjMJ3E3PDLuVug">Youtube</a></li>
              <li role="presentation" class=""><a href="https://www.livecoding.tv/lucasmrthomaz/">Livecoding.TV</a></li>
            </ul></div>
          <!-- Redes sociais -->

        </div></div>
  <!--| Main & Sidebar |-->

  </div></div>

</hr> 
</br></br>

<!-- Rodape -->
<footer>
  <center>
  Blog criado do zero por Lucas Thomaz - lucasmrthomaz@outlook.com
  </br>
  Este blog usa Rails 4 , Bootstrap SASS version, JQuery/UI e algumas coisas mais...
  </center></footer>
<!-- Rodape -->

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @post.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h4>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :titulo, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :titulo, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :corpo, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :corpo, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :categoria, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :categoria, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :autor, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :autor, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="page-header">
  <%= link_to posts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @post, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing post</h1>
</div>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="page-header">

  <%= link_to new_post_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo post
  <% end %>
  <h1></h1>

</div>

      <%= content_tag_for(:p, @posts) do |post|%>

          <h3><%= post.titulo %></h3>
          <span>Por: <%= post.autor %></span> </br>
          <span>Data: <%= post.created_at%></span> </br>

           <p>
           <center> <%= image_tag "logo.png", size: "200x200" %> </center>
           </br>
           <%= post.corpo %>
          </p>

          <p> Categoria: <%= post.categoria %> </p>

          <div class="well">
          
          <p>Comentarios do post: </p>
          </br>
          <!-- Listing current comments -->
                        
          <!-- END -->

          </br>

          <!-- Add a new comment in post-->
          <p>Faca um comentario:</p> </br>
          
          <!-- END -->

          </div>

          <div class="well">
            <%= link_to 'Exibir', post, class: 'btn btn-primary' %>
            <%= link_to 'Editar', edit_post_path(post) , class: 'btn btn-warning' %>
            <%= link_to 'Excluir', post, method: :delete, data: { confirm: 'Tem certeza?' } , class: 'btn btn-danger' %>
          </div>

          </br>

      <% end %>

app/views/posts/new.html.erb
<div class="page-header">
  <%= link_to posts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>Novo post</h1>
</div>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="page-header">
  <%= link_to posts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_post_path(@post), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1><%= @post.titulo %></h1>
</div>

<dl class="dl-horizontal">

  <dd><%= @post.corpo %></dd>

  <dt>Categoria:</dt>
  <dd><%= @post.categoria %></dd>

  <dt>Autor:</dt>
  <dd><%= @post.autor %></dd>

</dl>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>